# Generated by Django 4.1.2 on 2022-11-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('generation_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deliveries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentKind',
            fields=[
                ('id_kind', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'document_kind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentsDelivery',
            fields=[
                ('id_documents_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.TextField()),
                ('document_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'documents_delivery',
                'managed': False,
            },
        ),
    ]
